TheUnitGallery/Models/Artwork.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TheUnitGallery.Models
{
    public class Artwork
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public int ArtistId { get; set; }
        public Artist Artist { get; set; }

        [Required]
        public int GenreId { get; set; }
        public Genre Genre { get; set; }

        [Required]
        public int MediumId { get; set; }
        public Medium Medium { get; set; }

        public string Subject { get; set; }

        [StringLength(4, ErrorMessage = "Year must be 4 digits long"),MinLength(4, ErrorMessage = "Year must be 4 digits long")]
        public string Year { get; set; }


        public double CostPrice { get; set; }
        public double SalesPrice { get; set; }

        [Required]
        [JsonConverter(typeof(StringEnumConverter))]
        public ArtworkStatus ArtworkStatus { get; set; }

        public string IamgeLocation { get; set; }
    }
}

TheUnitGallery/ViewModels/UploadImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TheUnitGallery.ViewModels
{
    public class UploadImageViewModel
    {
        public int ArtworkId { get; set; }
        public HttpPostedFileBase Image { get; set; }
        public String Path { get; set; }

        public int X { get; set; }
        public int Y { get; set; }
        public int W { get; set; }
        public int H { get; set; }
    }
}

TheUnitGallery/Areas/CMS/Controllers/ArtworksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheUnitGallery.Models;
using TheUnitGallery.Areas.CMS.ViewModels;
using TheUnitGallery.ViewModels;

namespace TheUnitGallery.Areas.CMS.Controllers
{
    public class ArtworksController : Controller
    {
        private ApplicationDbContext _context { get; set; }
        private ImageHelper imgHelper = new ImageHelper();
        
        public ArtworksController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: IMS/Artwork
        public ActionResult Index()
        {
            return View();
        }

        // GET: IMS/Artwork/Edit/1
        public ActionResult Edit(int id)
        {
            var artworkInDb = _context.Artworks.SingleOrDefault(a => a.Id == id);

            if (artworkInDb == null)
                return HttpNotFound();

            var viewModel = new ArtworkFormViewModel
            {
                Artwork = artworkInDb,
            };

            return View("ArtworkForm", viewModel);
        }

        //GET ims/artworks/save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Artwork artwork)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new ArtworkFormViewModel
                {
                    Artwork = artwork
                };

                return View("ArtworkForm", viewModel);
            }

            if (artwork.Id == 0)
                _context.Artworks.Add(artwork);
            else
            {
                var artworkInDb = _context.Artworks.Single(c => c.Id == artwork.Id);

                artworkInDb.Title = artwork.Title;
                artworkInDb.Subject = artwork.Subject;
                artworkInDb.CostPrice = artwork.CostPrice;
                artworkInDb.SalesPrice = artwork.SalesPrice;
                artworkInDb.Year = artwork.Year;
                artworkInDb.ArtworkStatus = artwork.ArtworkStatus;

                artworkInDb.ArtistId = artwork.ArtistId;
                artworkInDb.GenreId = artwork.GenreId;
                artworkInDb.MediumId = artwork.MediumId;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: IMS/Artwork/Edit/1
        public ActionResult UploadImage(int id)
        {
            var viewModel = new UploadImageViewModel
            {
                ArtworkId = id
            };
   
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult UploadImage(int id, UploadImageViewModel viewModel)
        {
            var path = imgHelper.SaveImage(viewModel.Image);

            viewModel.Path = path;

            return View(viewModel);
        }
    }
}

TheUnitGallery/Areas/IMS/Controllers/ArtworksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheUnitGallery.Areas.IMS.ViewModels;
using TheUnitGallery.Models;

namespace TheUnitGallery.Areas.IMS.Controllers
{
    public class ArtworksController : Controller
    {
        private ApplicationDbContext _context { get; set; }
        
        public ArtworksController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: IMS/Artwork
        public ActionResult Index()
        {
            return View();
        }

        // GET: IMS/Artwork/New
        public ActionResult New()
        {
            var viewModel = new ArtworkFormViewModel
            {
                Artwork = new Artwork()
            };

            return View("ArtworkForm", viewModel);
        }

        // GET: IMS/Artwork/Edit/1
        public ActionResult Edit(int id)
        {
            var artworkInDb = _context.Artworks.SingleOrDefault(a => a.Id == id);

            if (artworkInDb == null)
                return HttpNotFound();

            var viewModel = new ArtworkFormViewModel
            {
                Artwork = artworkInDb,
            };

            return View("ArtworkForm", viewModel);
        }

        //GET ims/artworks/save
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Artwork artwork)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new ArtworkFormViewModel
                {
                    Artwork = artwork
                };

                return View("ArtworkForm", viewModel);
            }

            if (artwork.Id == 0)
                _context.Artworks.Add(artwork);
            else
            {
                var artworkInDb = _context.Artworks.Single(c => c.Id == artwork.Id);

                artworkInDb.Title = artwork.Title;
                artworkInDb.Subject = artwork.Subject;
                artworkInDb.CostPrice = artwork.CostPrice;
                artworkInDb.SalesPrice = artwork.SalesPrice;
                artworkInDb.Year = artwork.Year;
                artworkInDb.ArtworkStatus = artwork.ArtworkStatus;

                artworkInDb.ArtistId = artwork.ArtistId;
                artworkInDb.GenreId = artwork.GenreId;
                artworkInDb.MediumId = artwork.MediumId;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

TheUnitGallery/Controllers/API/ArtworksController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using TheUnitGallery.Dtos;
using TheUnitGallery.Models;


namespace TheUnitGallery.Controllers.API
{
    public class ArtworksController : ApiController
    {
        private ApplicationDbContext _context;

        public ArtworksController()
        {
            _context = new ApplicationDbContext();
        }

        //GET /api/Artworks
        public IHttpActionResult GetArtworks()
        {
            var artworkDtos = _context.Artworks
                .Include(a => a.Artist)
                .Include(a => a.Genre)
                .Include(a => a.Medium)
                .ToList()
                .Select(Mapper.Map<Artwork, ArtworkDto>);

            return Ok(artworkDtos);
        }

        //GET /api/Artworks/1
        public IHttpActionResult GetArtworks(int id)
        {
            var artwork = _context.Artworks.SingleOrDefault(c => c.Id == id);

            if (artwork == null)
                return NotFound();

            return Ok(Mapper.Map<Artwork, ArtworkDto>(artwork));
        }

        // POST /api/Artworks
        [HttpPost]
        public IHttpActionResult CreateArtwork(ArtworkDto artworkDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var artwork = Mapper.Map<ArtworkDto, Artwork>(artworkDto);

            _context.Artworks.Add(artwork);
            _context.SaveChanges();

            artworkDto.Id = artwork.Id;

            return Created(new Uri(Request.RequestUri + "/" + artwork.Id), artworkDto);
        }


        // PUT /api/Artworks/1
        public IHttpActionResult UpdateArtwork(int id, ArtworkDto artworkDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var artworkInDb = _context.Artworks.SingleOrDefault(c => c.Id == id);

            if (artworkInDb == null)
                return NotFound();

            Mapper.Map(artworkDto, artworkInDb);

            _context.SaveChanges();

            return Ok();
        }

        // DELETE /api/Artworks/1
        public IHttpActionResult DeleteArtwork(int id)
        {
            var artworkInDb = _context.Artworks.SingleOrDefault(c => c.Id == id);

            if (artworkInDb == null)
                return NotFound();

            _context.Artworks.Remove(artworkInDb);
            _context.SaveChanges();

            return Ok();
        }
    }
}

TheUnitGallery/Controllers/ArtworkController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheUnitGallery.Models;

namespace TheUnitGallery.Controllers
{
    public class ArtworkController : Controller
    {
        private ApplicationDbContext _context;

        public ArtworkController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Artwork
        public ActionResult Detail(int id)
        {
            var artwork = _context.Artworks
                .Include(a => a.Genre)
                .Include(a => a.Medium)
                .Include(a => a.Artist)
                .SingleOrDefault(a => a.Id == id);

            if (artwork == null)
                return RedirectToAction("Index", "Home", new { area = "" });

            return Content(artwork.Title);
        }
    }
}

TheUnitGallery/Areas/CMS/Views/Artworks/ArtworkForm.cshtml
@model TheUnitGallery.Areas.CMS.ViewModels.ArtworkFormViewModel

@using TheUnitGallery.Areas.CMS.ViewModels

<div class="row body-content">
    @Html.Partial("_CMSAdminNavPanel")
    <div class="col-sm-9 col-md-10">
        <div class="row">
            <div class="col-sm-12">
                <h3>@Model.Title</h3>
                <hr />
            </div>
        </div>
        @using (Html.BeginForm("Save", "Artworks"))
        {
            @Html.ValidationSummary()
            <div class="row">

                <div class="col-sm-12 col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Artwork.Title)
                        @Html.TextBoxFor(m => m.Artwork.Title, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Artwork.Subject)
                        @Html.TextBoxFor(m => m.Artwork.Subject, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Artwork.Year)
                        @Html.TextBoxFor(m => m.Artwork.Year, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Artwork.CostPrice)
                        @Html.TextBoxFor(m => m.Artwork.CostPrice, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Artwork.SalesPrice)
                        @Html.TextBoxFor(m => m.Artwork.SalesPrice, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.Artwork.Id)
                        @Html.HiddenFor(m => m.Artwork.GenreId)
                        @Html.HiddenFor(m => m.Artwork.ArtistId)
                        @Html.HiddenFor(m => m.Artwork.MediumId)
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>

                <div class="col-sm-12 col-md-6">
                    <div class="form-group">
                        <label for="artist-selection">Artist</label>
                        <select class="custom-select" id="artist-selection" required></select>
                    </div>
                    <div class="form-group">
                        <label for="genre-selection">Genre</label>
                        <select class="custom-select" id="genre-selection" required></select>
                    </div>
                    <div class="form-group">
                        <label for="medium-selection">Medium</label>
                        <select class="custom-select" id="medium-selection" required></select>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Artwork.ArtworkStatus, "Artwork Status", htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EnumDropDownListFor(model => model.Artwork.ArtworkStatus, "Select Status", new { @class = "form-control"})
                    </div><hr /><hr />
                    <div class="form-group">
                        <input type="text" class="form-control" id="new-medium-genre" value="Enter new Medium or Genre here" />
                    </div>
                    <button type="button" class="btn btn-primary btn-sm" id="add-medium">Add As Medium</button>
                    <button type="button" class="btn btn-primary btn-sm" id="add-genre">Add As Genre</button>
                    @*</div>*@
                </div>
            </div>
        }
    </div>
</div>


@section scripts
{
    <script>
        $(document).ready(function () {

            getGenres();
            getMediums();
            getArtists();

            //CHANGE HIDDEN FIELDS WHEN DROPDOWNS CHANGE
            $('#artist-selection').on('change', function () {
                $('#Artwork_ArtistId').attr('value', this.value);
            })

            $('#medium-selection').on('change', function () {
                $('#Artwork_MediumId').attr('value', this.value);
            })

            $('#genre-selection').on('change', function () {
                $('#Artwork_GenreId').attr('value', this.value);
            })


            //ADD GENRE

            $("#new-medium-genre").on('click', function () {
                $(this).val("");
            });

            $("#add-genre").on("click", function () {

                var name = $("#new-medium-genre").val()

                var newItem = {
                    name: name
                };

                $.ajax({
                    method: "POST",
                    url: "/api/genres",
                    contentType: "application/json",
                    data: JSON.stringify(newItem),
                    success: function () {
                        $('#genre-selection').empty();
                        getGenres();
                        bootbox.alert(name + " was succesfully added to Genres");
                        $("#new-medium-genre").val("Enter new Medium or Genre here...");
                    }
                });
            });

            //ADD MEDIUM
            $("#add-medium").on("click", function () {

                var name = $("#new-medium-genre").val()

                var newItem = {
                    name: name
                };

                $.ajax({
                    method: "POST",
                    url: "/api/mediums",
                    contentType: "application/json",
                    data: JSON.stringify(newItem),
                    success: function () {
                        $('#medium-selection').empty();
                        getMediums();
                        bootbox.alert(name + " was succesfully added to Mediums");
                        $("#new-medium-genre").val("Enter new Medium or Genre here...");
                    }
                });
            });


            //POPULATE DROPDOWN LISTS FROM API
            function getGenres() {
                $.ajax({
                    method: "GET",
                    url: "/api/genres/",

                    success: function (result) {
                        for (var i in result) {
                            $('#genre-selection').append($("<option></option>")
                                .attr("value", result[i].id)
                                .text(result[i].name)
                            );
                        }
                        $('#genre-selection').val($("#Artwork_GenreId").val());
                    }
                });
            }

            function getMediums() {
                $.ajax({
                    method: "GET",
                    url: "/api/mediums/",

                    success: function (result) {
                        for (var i in result) {
                            $('#medium-selection').append($("<option></option>")
                                .attr("value", result[i].id)
                                .text(result[i].name)
                            );
                        }
                            $('#medium-selection').val($("#Artwork_MediumId").val());
                    }
                });
            }

            function getArtists() {
                $.ajax({
                    method: "GET",
                    url: "/api/artists/",

                    success: function (result) {
                        for (var i in result) {
                            $('#artist-selection').append($("<option></option>")
                                .attr("value", result[i].id)
                                .text(result[i].firstName + " " + result[i].lastName)
                            );
                        }
                            $('#artist-selection').val($("#Artwork_ArtistId").val());
                    }
                });
            }
        });
    </script>
}

TheUnitGallery/Areas/CMS/Views/Artworks/Index.cshtml
@using TheUnitGallery.Models

@{
    ViewBag.Title = "Artwork Management";
}

<div class="row body-content">
    @Html.Partial("_CMSAdminNavPanel")
    <div class="col-sm-9 col-md-10">
        <h3>@ViewBag.Title</h3>
        <hr />
        <table class="table table-striped" id="artworks">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Artist</th>
                    <th>Status</th>
                    <th>Upload Images</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>


</div>

@section scripts
{
    <script>
        $(document).ready(function () {

            var table = $("#artworks").DataTable({
                ajax: {
                    url: "/api/artworks",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "title",
                        render: function (data, type, artwork) {
                            return "<a href='artworks/edit/" + artwork.id + "'>" + data + "</a>";
                        }
                    },
                    {
                        data: "artist",
                        render: function (data, type, artist) {
                            return data.firstName + " " + data.lastName;
                        }
                    },
                    {
                        data: "artworkStatus",
                        render: function (data) {
                            return data;
                        }
                    },
                    {
                        data: "id",
                        render: function (data) {
                            return "<a href='artworks/uploadimage/" + data + "' class='btn btn-outline-primary'>Upload Image</a>";
                        }
                    },
                ]


            });
        });

    </script>
}

TheUnitGallery/Areas/CMS/Views/Artworks/UploadImage.cshtml
@model TheUnitGallery.ViewModels.UploadImageViewModel

@using TheUnitGallery.ViewModels

@{
    ViewBag.Title = "UploadImage";
}

<div class="row body-content">
    @Html.Partial("_CMSAdminNavPanel")
    <div class="col-sm-9 col-md-10">
        <div class="row">
            <div class="col-sm-4 col-md-4">
                <h3>@ViewBag.Title</h3>
                <hr />
                @using (Html.BeginForm("UploadImage", "Artworks", FormMethod.Post, new { enctype = "multipart/form-data", id = Model.ArtworkId }))
    {
            <div class="form-group">
                @Html.LabelFor(m => m.Image)
                <input type="file" name="Image" />
            </div>
            <div class="form-group">
                @Html.HiddenFor(m => m.ArtworkId)
                @Html.HiddenFor(m => m.X)
                @Html.HiddenFor(m => m.Y)
                @Html.HiddenFor(m => m.W)
                @Html.HiddenFor(m => m.H)
            </div>
            <span id="XX">@Model.X</span><br />
            <span id="YY">@Model.Y</span><br />
            <span id="WW">@Model.W</span><br />
            <span id="HH">@Model.H</span><br />
            <button type="submit" class="btn btn-primary save-btn">Upload Image</button>
}
            </div>
            <div class="col-sm-8">
                @if (Model.Path != null)
    {
            <div class="crop-box">
                <img id="target" src="@Url.Content("~" + Model.Path)" />
            </div>
}
                <hr />
                <div class="form-group">
                    <button class="btn btn-success" Onclick="btnUpload_Click">Save File</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

@section scripts
{
<script language="Javascript">
    $(document).ready(function () {
        $('#target').Jcrop({
            boxWidth: 650,
            boxHeight: 600,
            bgColor: 'black',
            bgOpacity: .4,
            maxSize: [570, 462],
            setSelect: [0, 0, 570, 462],
            aspectRatio: 570 / 462,
            onSelect: storeCoords
        });

        function storeCoords(c) {
            $('#X').val(c.x);
            $('#Y').val(c.y);
            $('#W').val(c.w);
            $('#H').val(c.h);


            $('#XX').text(c.x);
            $('#YY').text(c.y);
            $('#WW').text(c.w);
            $('#HH').text(c.h);
        }
    });
</script>    
}